version: "3.4"

services:
  cookieprovider:
    image: cookieprovider:latest
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.cookieprovider.loadbalancer.server.port=3000"
      - "traefik.http.routers.cookieprovider.rule=Host(`vps.scottsemtner.com`) && PathPrefix(`/cookies`)"
      - "traefik.http.routers.cookieprovider.entrypoints=websecure"
      - "traefik.http.routers.cookieprovider.tls=true"
      - "traefik.http.routers.cookieprovider.tls.certresolver=myresolver"

  evals:
    image: ghcr.io/ssemtner/ucsd-student-evals:latest
    networks:
      - traefik-public
    stop_grace_period: 1s
    secrets:
      - service-url
      - db-password
      - cookies-token
    entrypoint: "/bin/sh -c 'export SERVICE_URL=$$(cat /run/secrets/service-url) && export DATABASE_URL=postgres://postgres:$$(cat /run/secrets/db-password)@postgres/evals && export && export COOKIES_TOKEN=$$(cat /run/secrets/cookies-token) && /app/ucsd-student-evals serve' && /app/ucsd-student-evals serve"

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.evals.loadbalancer.server.port=3000"
      - "traefik.http.routers.evals.rule=Host(`vps.scottsemtner.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.evals.entrypoints=websecure"
      - "traefik.http.routers.evals.tls=true"
      - "traefik.http.routers.evals.tls.certresolver=myresolver"
      - "traefik.http.middlewares.evals-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.evals.middlewares=evals-stripprefix"

  postgres:
    image: postgres:17
    networks:
      - traefik-public # FIXME:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: evals
    volumes:
      - pg-data:/var/lib/postgresql/data
    secrets:
      - db-password

  duo-client:
    image: duo-adb:latest
    networks:
      - traefik-public
    environment:
      DUO_AUTH_TOKEN_FILE: /run/secrets/duo-token
      ADB_HOST: adb-proxy
      ADB_PORT: 5555
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.duo-client.loadbalancer.server.port=8000"
      - "traefik.http.routers.duo-client.rule=Host(`duo.cmov.dev`)"
      - "traefik.http.routers.duo-client.entrypoints=websecure"
      - "traefik.http.routers.duo-client.tls=true"
      - "traefik.http.routers.duo-client.tls.certresolver=myresolver"

volumes:
  pg-data:

secrets:
  db-password:
    external: true
  service-url:
    external: true
  proxy-password:
    external: true
  cookies-token:
    external: true
  duo-token:
    external: true

networks:
  traefik-public:
    external: true
